README.md
close #2 
- 프로젝트 README.md 컨벤션 작성
=> [공통] 프로젝트 README 작성

BE/newsainturtle/src/main/java/com/newsainturtle/user/entity/User.java
=> [BE] feat: User Entity 생성

BE/newsainturtle/src/main/java/com/newsainturtle/common/config/WebConfig.java
=> [BE] Cors 설정 

BE/newsainturtle/src/main/java/com/newsainturtle/friend/entity/Friend.java
close #20 
- Friend 폴더 생성
- 친구 엔티티 생성
=> [BE] 친구 엔티티 생성

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Schedule.java
=> [BE] Schedule Entity 생성

BE/newsainturtle/src/main/java/com/newsainturtle/common/dto/BaseResponse.java
close #29
- 기본 Response Dto 형식 정의
=> [BE] BaseResponse.class 작성 

BE/newsainturtle/src/main/java/com/newsainturtle/user/entity/User.java
close #33
- User Entity 친구, 알림 리스트 추가
=> [BE] User Entity 수정

BE/newsainturtle/src/main/java/com/newsainturtle/alarm/controller/AlramController.java, BE/newsainturtle/src/main/java/com/newsainturtle/alarm/dto/AlarmRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/alarm/entity/Alarm.java, BE/newsainturtle/src/main/java/com/newsainturtle/alarm/exception/AlarmException.java, BE/newsainturtle/src/main/java/com/newsainturtle/alarm/repository/AlarmRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/alarm/service/AlarmService.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/controller/NotificationController.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/dto/NotificationRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/entity/FriendNotification.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/entity/Notification.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/entity/ScheduleNotification.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/exception/NotificationException.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/repository/NotificationRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/service/NotificationService.java
close #24
- 알림 도메인명 변경
- 알림 엔티티 생성
- 알림 엔티티 상속 클래스 생성
=> [BE] 알림 엔티티 생성

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Region.java
=> [BE] Region Entity 생성

BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/EmailDuplicateCheckRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/EmailDuplicateCheckResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/entity/User.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/repository/UserRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/service/UserService.java, BE/newsainturtle/src/test/java/com/newsainturtle/auth/controller/AuthControllerTest.java, BE/newsainturtle/src/test/java/com/newsainturtle/user/repository/UserRepositoryTest.java, BE/newsainturtle/src/test/java/com/newsainturtle/user/service/UserServiceTest.java
close #
- 이메일 중복 검사 Api Repository, Service 테스트 코드 작성
=> [BE] 이메일 중복검사 Repository, Sevice 테스트 코드 작성

FE/public/index.html, FE/src/app/store.ts, FE/src/components/css/Modal.module.css, FE/src/features/schedule/create/Create.tsx, FE/src/features/schedule/create/CreateLeft.tsx, FE/src/features/schedule/create/CreateRight.tsx, FE/src/pages/MapPage.tsx, FE/src/slices/mapSlice.ts
close #39 
- 일정생성1 페이지 지도 연결 및 생성
- map관련 redux 추가
- 모달 z-idex 수정(모달이 지도 뒤로 생성돼서 수정 했습니다)
=> [FE] 일정 생성1 - 지도 연결하기

BE/newsainturtle/build.gradle, BE/newsainturtle/src/main/java/com/newsainturtle/common/dto/BaseResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/friend/dto/UserSearchRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/friend/dto/UserSearchResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/friend/service/FriendService.java, BE/newsainturtle/src/test/java/com/newsainturtle/friend/service/FriendServiceTest.java
#34 
- 사용자 검색 서비스 테스트 코드 작성
- 사용자 검색 서비스 프로덕션 코드 작성
=> [BE] 사용자 검색 서비스 코드 작성

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/BasicLocation.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/CustomLocation.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Location.java
=> [BE] 장소 Entity 생성

FE/src/App.tsx, FE/src/components/Header.tsx, FE/src/features/user/login/Login.module.css, FE/src/features/user/login/Login.tsx, FE/src/features/user/login/LoginSocial.tsx, FE/src/pages/LoginPage.tsx
=> [FE] 로그인 페이지 컴포넌트 생성

FE/src/App.tsx, FE/src/components/Header.tsx, FE/src/features/user/login/Login.module.css, FE/src/features/user/login/Login.tsx, FE/src/features/user/regist/Regist.module.css, FE/src/features/user/regist/Regist.tsx, FE/src/pages/RegistPage.tsx
close #56 
- 회원가입 페이지 컴포넌트 생성 (기능 X)
- 로그인 페이지 새 창으로 열림
- 로그인 & 회원가입 페이지에서 헤더 숨김
=> [FE] 회원가입 페이지 컴포넌트 생성

BE/newsainturtle/src/main/java/com/newsainturtle/auth/AuthConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/controller/AuthController.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/LoginRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/LoginResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/exception/UnauthorizedUserException.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/service/AuthService.java, BE/newsainturtle/src/main/java/com/newsainturtle/common/security/JwtTokenProvider.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/entity/User.java, BE/newsainturtle/src/test/java/com/newsainturtle/auth/service/AuthServiceTest.java
close #52
- 로그인 서비스 테스트 코드 작성
- 로그인 api 작성
- 로그인 서비스 예외처리
=> [BE] 로그인 API 작성

BE/newsainturtle/src/main/java/com/newsainturtle/auth/constant/AuthConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/controller/AuthController.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/EmailDuplicateCheckRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/EmailDuplicateCheckResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/UserJoinRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/UserJoinResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/exception/NoEmailCheckException.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/entity/User.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/service/UserService.java, BE/newsainturtle/src/test/java/com/newsainturtle/user/repository/UserRepositoryTest.java, BE/newsainturtle/src/test/java/com/newsainturtle/user/service/UserServiceTest.java
close #57
- 로그인 API 테스트 / 프로덕션 코드 작성
=> [BE] 회원가입 API 작성

FE/src/App.tsx, FE/src/features/user/myPage/myProfile/MyProfile.module.css, FE/src/features/user/myPage/myProfile/MyProfile.tsx, FE/src/features/user/myPage/myProfile/MyProfileEdit.tsx
close #61 
- 프로필 수정 페이지 컴포넌트 생성 및 배치 (기능x)
=> [FE] 프로필 수정 페이지 컴포넌트 생성 및 배치

BE/newsainturtle/src/main/java/com/newsainturtle/common/constant/CommonConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/common/exception/JwtException.java, BE/newsainturtle/src/main/java/com/newsainturtle/friend/constant/FriendConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/friend/controller/FriendController.java, BE/newsainturtle/src/main/java/com/newsainturtle/friend/dto/UserSearchRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/friend/dto/UserSearchResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/friend/service/FriendService.java, BE/newsainturtle/src/test/java/com/newsainturtle/friend/service/FriendServiceTest.java
close #34
- 사용자 검색 시 탈퇴한 사용자 처리 테스트 코드 추가 
- 사용자 검색 프로덕션 코드 추가
=> [BE] 사용자 검색 API 작성

FE/src/features/user/myPage/mySchedule/MySchedule.module.css, FE/src/features/user/myPage/mySchedule/MySchedule.tsx, FE/src/features/user/myPage/mySchedule/MyScheduleList.tsx, FE/src/features/user/myPage/mySchedule/MyScheduleListItem.tsx
close #65 
- 나의 일정 아이템 컴포넌트 생성 및 배치
=> [FE] 프로필 일정 페이지 컴포넌트 생성 및 배치

BE/newsainturtle/src/main/java/com/newsainturtle/auth/exception/NoEmailCheckException.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/constant/UserConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/controller/UserController.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/dto/UserInfoResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/service/UserService.java, BE/newsainturtle/src/test/java/com/newsainturtle/user/repository/UserRepositoryTest.java, BE/newsainturtle/src/test/java/com/newsainturtle/user/service/UserServiceTest.java
close #68
- 마이 페이지 조회 API 테스트/프로덕션 코드 작성
=> [BE] 마이페이지 조회 API 작성

BE/newsainturtle/src/main/java/com/newsainturtle/user/constant/UserConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/controller/UserController.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/dto/ModifyProfileRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/dto/ProfileResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/entity/User.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/service/UserService.java, BE/newsainturtle/src/test/java/com/newsainturtle/user/repository/UserRepositoryTest.java, BE/newsainturtle/src/test/java/com/newsainturtle/user/service/UserServiceTest.java
close #74
- [] 코드 개선
- 프로필 사진 수정/등록 API 테스트/프로덕션 코드 작성
=> [BE] 프로필 사진 수정/등록 API 작성

BE/newsainturtle/src/main/java/com/newsainturtle/friend/controller/FriendController.java, BE/newsainturtle/src/main/java/com/newsainturtle/friend/dto/UserSearchResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/friend/repository/FriendRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/friend/service/FriendService.java, BE/newsainturtle/src/test/java/com/newsainturtle/friend/repository/FriendRepositoryTest.java, BE/newsainturtle/src/test/java/com/newsainturtle/friend/service/FriendServiceTest.java
close #75
- 사용자 검색 시 사용자와의 관계를 나타내는 응답값 추가
=> [BE] 사용자 검색 API 수정

FE/src/features/main/Components/MainDestinationModal.tsx, FE/src/features/main/Main.module.css, FE/src/features/main/MainDestinationsFilter.tsx, FE/src/features/main/MainDestinationsItem.tsx, FE/src/features/main/MainDestinationsList.tsx, FE/src/features/main/MainDisplay.tsx, FE/src/styles/colorPalette.ts
close #72 
- 메인페이지 스텝 컴포넌트 수정 및 배치
- 메인페이지 여행지 아이템 모달창 생성
- 메인페이지 여행지 아이템 호버 시 이미지 확대 기능
- 메인페이지 여행지 정렬 버튼 생성
- 컬러팔레트 색상 추가 (LightGray(#999999), DarkGray(#666666))
=> [FE] 메인페이지 컴포넌트 수정 및 배치

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/constant/ScheduleErrorConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/constant/ScheduleSuccessConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/RegionController.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/ScheduleController.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/RegionRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/RegionResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Region.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/exception/DuplicateException.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/exception/NullException.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/exception/ScheduleException.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/RegionRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/ScheduleRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/RegionService.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java, BE/newsainturtle/src/test/java/com/newsainturtle/schedule/repository/RegionRepositoryTest.java, BE/newsainturtle/src/test/java/com/newsainturtle/schedule/service/RegionServiceTest.java
=> [BE] 지역 API 작성

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/ScheduleMember.java
=> [BE] ScheduleMember Entity 생성

BE/newsainturtle/src/main/java/com/newsainturtle/friend/constant/FriendConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/friend/controller/FriendController.java, BE/newsainturtle/src/main/java/com/newsainturtle/friend/dto/FriendFollowRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/friend/exception/UnableToRequestFriendFollowException.java, BE/newsainturtle/src/main/java/com/newsainturtle/friend/service/FriendService.java, BE/newsainturtle/src/test/java/com/newsainturtle/friend/service/FriendServiceTest.java
close #40
- 친구 요청 API 작성
- 친구 요청 후 알림 메세지 보내는 부분은 알림 API 작성 후 추가 예정
=> [BE] 친구 요청 API 작성

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Schedule.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/ScheduleRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/constant/UserConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/controller/UserController.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/dto/ModifyScheduleNameRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/service/UserService.java, BE/newsainturtle/src/test/java/com/newsainturtle/user/repository/UserRepositoryTest.java, BE/newsainturtle/src/test/java/com/newsainturtle/user/service/UserServiceTest.java
close #82
- 여행 이름 수정 API 테스트/프로덕션 코드 작성
=> [BE] 여행 이름 수정 API 테스트/프로덕션 코드 작성

BE/newsainturtle/src/main/java/com/newsainturtle/friend/constant/FriendConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/friend/controller/FriendController.java, BE/newsainturtle/src/main/java/com/newsainturtle/friend/dto/FriendInfoResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/friend/dto/FriendListResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/friend/repository/FriendRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/friend/service/FriendService.java, BE/newsainturtle/src/test/java/com/newsainturtle/friend/repository/FriendRepositoryTest.java, BE/newsainturtle/src/test/java/com/newsainturtle/friend/service/FriendServiceTest.java
close #87
- 친구 목록 조회 테스트 코드 작성
- 친구 목록 조회 프로덕션 코드 작성
=> [BE] 친구 목록 조회 API 작성

FE/src/components/Button.tsx, FE/src/features/schedule/create/CreateInfo.module.css, FE/src/features/schedule/create/CreateInfo.tsx, FE/src/features/schedule/create/CreateSearch.tsx, FE/src/features/schedule/create/info/Info.module.css, FE/src/features/schedule/create/info/InfoListHotel.tsx, FE/src/features/schedule/create/info/InfoListPlace.tsx, FE/src/features/schedule/create/search/Search.module.css, FE/src/features/schedule/create/search/SearchCardInfoModal.tsx, FE/src/features/schedule/create/search/SearchInput.tsx, FE/src/features/schedule/create/search/SearchList.tsx, FE/src/features/schedule/create/search/SearchListCard.tsx, FE/src/features/schedule/create/search/SearchRadioBtn.tsx, FE/src/pages/MapPage.tsx
close #69 
- 일정 생성 우측 부분 컴포넌트 생성 및 배치
- 추천/검색 결과 리스트 컴포넌트 생성
- 검색 목록 카드 모달 생성
- 호텔/장소 버튼 선택과 검색 버튼 클릭 여부에 따라 리스트 변경 기능
- 선택한 호텔/장소 redux 저장 및 보여주기
- InfoListPlace 리팩토링(useMemo 사용으로 불필요한 렌더링 줄이기)
=> [FE] 일정 생성 페이지 검색 컴포넌트 생성 및 배치

FE/src/app/store.ts, FE/src/components/Button.tsx, FE/src/components/Header.tsx, FE/src/features/user/notice/Notice.module.css, FE/src/features/user/notice/Notice.tsx, FE/src/features/user/notice/NoticeItem.tsx, FE/src/slices/noticeSlice.ts
close #91 
- 알림 컴포넌트 생성 및 배치
- 알림 slice 생성
- 알림 목록 전체 삭제 기능 추가
- 알림 목록 개별 삭제 기능 추가
- 공통 컴포넌트 버튼 회색 추가
=> [FE] 알림 모달 컴포넌트 생성 및 배치

BE/newsainturtle/src/main/java/com/newsainturtle/friend/constant/FriendConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/friend/controller/FriendController.java, BE/newsainturtle/src/main/java/com/newsainturtle/friend/dto/FriendRemoveRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/friend/exception/NotFriendRelationException.java, BE/newsainturtle/src/main/java/com/newsainturtle/friend/exception/UnauthorizedFriendException.java, BE/newsainturtle/src/main/java/com/newsainturtle/friend/repository/FriendRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/friend/service/FriendService.java, BE/newsainturtle/src/test/java/com/newsainturtle/friend/repository/FriendRepositoryTest.java, BE/newsainturtle/src/test/java/com/newsainturtle/friend/service/FriendServiceTest.java
close #94
- 친구 삭제 API 작성
- 친구 삭제 관련 테스트코드 작성
=> [BE] 친구 삭제 API 작성

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Schedule.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/ScheduleLocation.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/ScheduleMember.java
=> [BE] 일정에포함된장소 엔티티 생성

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/ScheduleMember.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/ScheduleMemberRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/constant/UserConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/controller/UserController.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/dto/ScheduleListResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/service/UserService.java, BE/newsainturtle/src/test/java/com/newsainturtle/schedule/repository/ScheduleMemberRepositoryTest.java, BE/newsainturtle/src/test/java/com/newsainturtle/user/service/UserServiceTest.java
close #95
- 일정 목록 조회 API 테스트/프로덕션 코드 작성
=> [BE] 일정 목록 조회 API 테스트/프로덕션 코드 작성

FE/src/features/user/login/Login.tsx, FE/src/features/user/login/LoginSocial.tsx, FE/src/features/user/myPage/myProfile/MyProfileEdit.tsx, FE/src/features/user/regist/Regist.tsx
close #85 
- 로그인 및 회원가입 유효성 검사 로직
- 프로필 수정 시 이메일 수정 불가
=> [FE] 로그인 및 회원가입 유효성 검사 생성

FE/package-lock.json, FE/src/App.tsx, FE/src/app/store.ts, FE/src/components/Header.tsx, FE/src/features/schedule/ScheduleRouter.tsx, FE/src/features/schedule/create/info/InfoCalendar.tsx, FE/src/features/schedule/create/info/InfoDate.tsx, FE/src/features/schedule/create/info/InfoListHotel.tsx, FE/src/features/schedule/create/info/InfoListPlace.tsx, FE/src/features/schedule/create/info/InfoLocal.tsx, FE/src/features/schedule/create/search/SearchListCard.tsx, FE/src/features/schedule/edit/EditFullScheduleList.tsx, FE/src/pages/ScheduleCreatePage.tsx, FE/src/pages/ScheduleEditPage.tsx, FE/src/slices/scheduleCreateSlice.ts, FE/src/styles/colorPalette.ts
close #96 
- 일정 생성 관련 파일명 scheduleCreate로 모두 변경
- slice 사용 통일 - scheduleCreateSlice변경
- gray 컬러 추가, 패키지 설치 파일
=> [FE] 일정 생성 파일 이름 변경 및 slice 통일 

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Schedule.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/constant/UserConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/controller/UserController.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/service/UserService.java, BE/newsainturtle/src/test/java/com/newsainturtle/user/service/UserServiceTest.java
close #104
- 일정 공개 여부 수정 API 테스트/프로덕션 코드 작성
=> [BE] 일정 공개 여부 수정 API 테스트/프로덕션 코드 작성

BE/newsainturtle/src/main/java/com/newsainturtle/notification/constant/NotificationConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/controller/NotificationController.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/dto/NotificationListResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/dto/NotificationRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/dto/NotificationResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/entity/Notification.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/entity/NotificationStatus.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/exception/NoResponseNotificationException.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/exception/NotUserOwnNotificationException.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/exception/NotificationException.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/repository/NotificationRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/service/NotificationService.java, BE/newsainturtle/src/test/java/com/newsainturtle/notification/repository/NotificationRepositoryTest.java, BE/newsainturtle/src/test/java/com/newsainturtle/notification/service/NotificationServiceTest.java
close #112
- 알림 상태 enum을 엔티티 외부로 분리함
- 사용자가 응답한 알림 전체 삭제 테스트 코드 작성
- 사용자가 응답한 알림 전체 삭제 API 작성
=> [BE] 사용자가 응답한 알림 전체 삭제 API 작성

BE/newsainturtle/src/main/java/com/newsainturtle/notification/constant/NotificationConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/controller/NotificationController.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/dto/NotificationListResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/dto/NotificationResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/entity/Notification.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/repository/NotificationRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/service/NotificationService.java, BE/newsainturtle/src/test/java/com/newsainturtle/notification/repository/NotificationRepositoryTest.java, BE/newsainturtle/src/test/java/com/newsainturtle/notification/service/NotificationServiceTest.java
close #103
- 알림 API 작성
- 알림 엔티티 수정 (알림 상태 boolean에서 enum으로 변경)
- 알림 조회 테스트 코드 작성
=> [BE] 알림 조회 API 작성

BE/newsainturtle/src/main/java/com/newsainturtle/notification/constant/NotificationConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/controller/NotificationController.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/dto/NotificationListResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/dto/NotificationRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/dto/NotificationResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/entity/Notification.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/exception/NoResponseNotificationException.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/exception/NotUserOwnNotificationException.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/exception/NotificationException.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/repository/NotificationRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/service/NotificationService.java, BE/newsainturtle/src/test/java/com/newsainturtle/notification/repository/NotificationRepositoryTest.java, BE/newsainturtle/src/test/java/com/newsainturtle/notification/service/NotificationServiceTest.java
close #110
- 알림 개별 삭제 API 작성
- 알림 개별 삭제 관련 테스트코드 작성
- 커스텀 예외처리를 위해서 deleteBy~ 대신 Query문 직접 작성
=> [BE] 알림 개별 삭제 API 작성

FE/src/features/schedule/create/CreateInfo.tsx, FE/src/features/schedule/create/CreateMap.tsx, FE/src/features/schedule/create/CreateSearch.tsx, FE/src/features/schedule/create/info/InfoCalendar.tsx, FE/src/features/schedule/create/info/InfoListHotel.tsx, FE/src/features/schedule/create/info/InfoListPlace.tsx, FE/src/features/schedule/create/search/Search.module.css, FE/src/features/schedule/create/search/SearchList.tsx, FE/src/features/schedule/create/search/SearchListCard.tsx, FE/src/pages/ScheduleCreatePage.tsx, FE/src/slices/scheduleCreateSlice.ts
close #106 
- 선택 목록 맞게 목록 데이터 추가하기
- 선택한 호텔 일정에 호텔 데이터 추가
- 선택한 출발지와 종착지에 장소 데이터 추가
- 호텔 선택 리스트 컴포넌트 코드 스타일 변경
- 호텔/장소 선택 삭제 slice reducer코드 제거
- 지도 컴포넌트 파일로 분리 생성
=> [FE] 일정 생성 제어 버튼에 따른 목록 추가 기능

FE/src/features/user/myPage/myFriends/MyFriends.module.css, FE/src/features/user/myPage/myFriends/MyFriends.tsx, FE/src/features/user/myPage/myFriends/MyFriendsAdd.tsx, FE/src/features/user/myPage/myFriends/MyFriendsSearchItem.tsx
close #97  
- 친구 검색 모달 컴포넌트 생성 및 배치
=> [FE] 친구 검색 모달 컴포넌트 생성 및 배치

FE/src/components/Button.tsx, FE/src/features/user/notice/Notice.module.css, FE/src/features/user/notice/Notice.tsx, FE/src/features/user/notice/NoticeItem.tsx, FE/src/slices/noticeSlice.ts
close #116 
- 알림 slice 값 추가
- 공통 컴포넌트 버튼 텍스트 색상 조건문 수정
- 알림 컴포넌트 디자인 수정
=> [FE] 알림 컴포넌트 디자인 수정

FE/src/features/schedule/edit/EditDayScheduleList.tsx, FE/src/pages/ScheduleEditPage.tsx
close #117 
-일자별 장소 리스트 없을 시 순서 변경 오류 해결
=> [FE] 일정 수정 시 일자별 장소 리스트 없을 경우 순서 변경 오류 해결

BE/newsainturtle/src/main/java/com/newsainturtle/NewsainturtleApplication.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Schedule.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/ScheduleMember.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/service/UserService.java
=> [BE] 일정생성시 포함된 멤버추가 API 작성

BE/newsainturtle/src/main/java/com/newsainturtle/friend/service/FriendService.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/entity/Notification.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/repository/NotificationRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/service/NotificationService.java, BE/newsainturtle/src/test/java/com/newsainturtle/friend/service/FriendServiceTest.java, BE/newsainturtle/src/test/java/com/newsainturtle/notification/repository/NotificationRepositoryTest.java, BE/newsainturtle/src/test/java/com/newsainturtle/notification/service/NotificationServiceTest.java
close #122
- 알림 생성 서비스 코드 작성
- 알림 상태 변경 서비스 코드 작성
- 알림 서비스 함수 호출하도록 친구 서비스 코드 수정
=> [BE] 친구 요청 알림 생성 관련 코드 작성

FE/src/api/Api.ts, FE/src/api/JsonAxios.ts, FE/src/api/MultipartAxios.ts
=> [FE] 공통 API 파일 생성

BE/newsainturtle/src/main/java/com/newsainturtle/auth/controller/AuthController.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/UserJoinRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/dto/ScheduleListResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/service/UserService.java
close #131
- 이메일 중복검사 API HTTP메소드 변경
- 일정 목록 조회 시 반환 정보 추가
- 비밀번호 변경 시 로직 변경
=> [BE] 유저 및 마이페이지 API 수정

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/constant/ScheduleSuccessConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/ScheduleController.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/LocationResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleLocationResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
=> [BE] 일정 조회 API 작성

BE/newsainturtle/src/main/java/com/newsainturtle/friend/repository/FriendRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/constant/NotificationConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/controller/NotificationController.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/dto/NotificationResponseRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/exception/NotificationResponseBadRequestException.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/service/NotificationService.java, BE/newsainturtle/src/test/java/com/newsainturtle/friend/repository/FriendRepositoryTest.java, BE/newsainturtle/src/test/java/com/newsainturtle/notification/service/NotificationServiceTest.java
close #127 
- 친구 요청 알림 응답 처리를 위한 코드 작성
=> [BE] 친구 요청 알림 처리 API 작성

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/ScheduleController.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
=> [BE] 메인페이지에서 일정 생성 API

FE/src/api/JsonAxios.ts, FE/src/api/MultipartAxios.ts, FE/src/slices/authSlice.ts
- axios header Authorization 오류 해결
=> [FE] axios header Authorization 오류 해결

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/constant/ScheduleSuccessConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/ScheduleController.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/SchedulePeriodRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleStartEndLocationRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleVehicleRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Schedule.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
close #140 
- 일정 생성 1 - 일정 시작/끝 날짜 변경 API
- 일정 생성 1 - 일정 시작/끝 장소 변경 API
- 일정 생성 1 - 이동수단 변경 API
=> [BE] 일정생성 1 - 일정 기본 정보 변경 API 작성

BE/newsainturtle/src/main/java/com/newsainturtle/friend/service/FriendService.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/repository/FriendNotificationRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/repository/NotificationRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/repository/ScheduleNotificationRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/service/NotificationService.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/constant/ScheduleErrorConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/constant/ScheduleSuccessConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/ScheduleController.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/InviteFriendRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/exception/UnableToRequestFriendInviteException.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/ScheduleMemberRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java, BE/newsainturtle/src/test/java/com/newsainturtle/notification/repository/NotificationRepositoryTest.java
close #126 
- 일정 초대 알림 생성 API 작성
- 알림 레포지토리 분리 (알림, 친구요청알림, 일정초대알림)
=> [BE] 일정 초대 알림 생성 API 작성

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/constant/ScheduleErrorConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/constant/ScheduleSuccessConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/ScheduleController.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/FriendInfoResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/FriendListResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/exception/UninvitedUsersException.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
close #142 
- 일정 공유 친구 목록 조회 API 작성
=> [BE] 일정 공유 친구 목록 조회 API 작성

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/constant/ScheduleSuccessConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/ScheduleController.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/LocationResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/LocationSearchRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Location.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/LocationRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
=> [BE] 호텔/장소 검색 API 작성

FE/src/components/Header.tsx, FE/src/features/user/login/Login.tsx, FE/src/features/user/myPage/myProfile/MyProfile.tsx, FE/src/features/user/myPage/myProfile/MyProfileEdit.tsx, FE/src/features/user/regist/Regist.tsx, FE/src/slices/authSlice.ts
close #135
- 이메일, 비밀번호 유효성 수정
- 유저 정보 API 연결
- 유저 정보 수정 API 연결
=> [FE] 마이페이지 유저 정보 API 연결

BE/newsainturtle/src/main/java/com/newsainturtle/notification/service/NotificationService.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
close #148
- 알림 처리 API 수정 (일정 초대 알림 처리 서비스 추가)
- 일정 초대 서비스 예외처리 수정 (일정 공유된 사용자가 아닐경우 다른 예외를 반환하도록 함)
=> [BE] 일정 초대 알림 처리 API 작성

FE/src/app/store.ts, FE/src/features/schedule/create/info/InfoCalendar.tsx, FE/src/index.tsx, FE/src/pages/ScheduleCreatePage.tsx
close #157 
- 로그인 정보 로컬 자동저장 안되게 해결
- 일정 생성 페이지 가로 너비 반응형 안 되는 이슈 해결
- 날짜 기간 선택 11일에서 10일까지 가능으로 변경
=> [FE] 사용자 정보 로컬 자동 저장 해결 & 일정 생성 페이지 이슈 수정

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/RegionController.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/RegionRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/RegionResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Region.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/RegionService.java
=> [BE] 메인 장소 API 컬럼 추가

FE/src/api/Api.ts, FE/src/features/user/notice/Notice.tsx, FE/src/features/user/notice/NoticeItem.tsx, FE/src/slices/noticeSlice.ts
close #162 
- 알림 전체 삭제 API 연결
- API 파일 알림 변수명 변경
- noticeSlice 변수명 백엔드와 통일
- 알림 조회 API 연결
- 알림 처리 API 연결
- 알림 개별 삭제 API 연결
=> [FE] 알림 API 연결

FE/src/features/user/myPage/myFriends/MyFriends.tsx, FE/src/features/user/myPage/myProfile/MyProfile.tsx, FE/src/slices/friendSlice.ts
close #169 
- 친구 목록 초기 데이터 초기화
- 마이페이지 프로필에 친구 수 정보 추가
- 친구 목록, 친구 수 friendSlice에 저장
=> [FE] 친구 API 연결 오류 해결

BE/newsainturtle/DockerFile, FE/DockerFile
=> [BE] DokcerFile 생성

BE/newsainturtle/src/main/java/com/newsainturtle/common/config/SecurityConfig.java
close #181
- 메인페이지 지역 조회 api 로그인 하지 않고도 이용할 수 있도록 변경
=> [BE] 메인페이지 지역 목록 조회 api 수정

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/ScheduleController.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
=> [BE] 일정 생성 API 작성

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/ScheduleMemberRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/constant/UserConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/controller/UserController.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/exception/NotHostException.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/service/UserService.java
=> [BE] 일정 삭제 API 작성

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/ScheduleMemberRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/controller/UserController.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/service/UserService.java, BE/newsainturtle/src/test/java/com/newsainturtle/user/service/UserServiceTest.java
close #191
- 일정 정보 수정 시 호스트만 가능하도록 변경
=> [BE] 일정 정보 수정 시 호스트만 가능하도록 변경

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
=> [BE] 일정 생성시 멤버 추가 API 작성

BE/newsainturtle/src/main/java/com/newsainturtle/notification/repository/ScheduleNotificationRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/service/UserService.java
close #189 
- 일정 삭제 시 관련 일정초대 알림 삭제
=> [BE] 일정 삭제 시 관련 일정초대 알림 삭제

BE/newsainturtle/src/main/java/com/newsainturtle/auth/constant/AuthConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/controller/AuthController.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/TokenCheckRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/TokenCheckResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/exception/InvalidTokenException.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/service/AuthService.java, BE/newsainturtle/src/main/java/com/newsainturtle/common/security/JwtAuthenticationFilter.java, BE/newsainturtle/src/main/java/com/newsainturtle/common/security/JwtTokenProvider.java
close #190 
- 토큰 유효성 체크 API 작성
- JWT 유효성 검증 로직 수정
- 유효하지 않은 토큰 예외처리
=> [BE] 토큰 유효성 검사 API 작성

BE/newsainturtle/src/main/java/com/newsainturtle/friend/repository/FriendRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/repository/FriendNotificationRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/constant/UserConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/controller/UserController.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/entity/User.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/service/UserService.java
=> [BE] 회원 탈퇴 API 작성

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/LocationController.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/LocationRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/BasicLocationRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/CustomLocationRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/LocationService.java
=> [BE] 장소 검색 API 작성

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/constant/ScheduleErrorConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/LocationController.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/exception/NotFoundException.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/LocationService.java
=> [BE] 장소 상세 조회 API 작성

BE/newsainturtle/build.gradle, BE/newsainturtle/src/main/java/com/newsainturtle/auth/constant/AuthConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/controller/AuthController.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/KakaoCodeUrlResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/kakao/KakaoInfoMapResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/kakao/KakaoInfoResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/kakao/KakaoNicknameResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/kakao/KakaoTokenResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/exception/KakaoLoginException.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/exception/UnavailableEmailException.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/service/AuthService.java
close #202
- 카카오 로그인 관련 API 작성
- WebClient 사용을 위한 의존성 추가
=> [BE] 카카오 로그인 API 작성

FE/src/features/schedule/edit/Edit.module.css, FE/src/features/schedule/edit/EditDayScheduleList.tsx, FE/src/features/schedule/edit/EditFullScheduleList.tsx, FE/src/features/schedule/edit/EditScheduleItem.tsx, FE/src/pages/ScheduleCreatePage.tsx, FE/src/pages/ScheduleEditPage.tsx, FE/src/slices/scheduleCreateSlice.ts, FE/src/slices/scheduleEditSlice.ts
close #208 
- 일정 데이터 연동 위해 일정 생성 redux 변경
- 일정 수정 페이지 내 여행 지역 출력 오류 수정
- 일정 저장 버튼 생성
- 일정 데이터 연동 기능 구현
=> [FE] 일정 수정 페이지로 데이터 연동

FE/src/api/Api.ts, FE/src/api/JsonAxios.ts, FE/src/app/store.ts, FE/src/components/Loading.tsx, FE/src/features/user/login/Login.tsx, FE/src/features/user/login/LoginSocial.tsx, FE/src/index.tsx
close #205 
- redux persist 적용 -> 로그인 시 localstorage에 사용자 정보 저장
- 로딩 컴포넌트 생성 및 카카오 로그인 시 적용
- 카카오 로그인 API 연결
=> [FE] 카카오 로그인 API 연결

FE/src/pages/ScheduleEditPage.tsx
=> [FE] 최종 일정 생성 API 연결

FE/src/api/JsonAxios.ts, FE/src/components/Header.tsx, FE/src/features/user/myPage/mySchedule/MySchedule.module.css, FE/src/features/user/myPage/mySchedule/MySchedule.tsx, FE/src/features/user/myPage/mySchedule/MyScheduleList.tsx, FE/src/features/user/myPage/mySchedule/MyScheduleListItem.tsx
close #172 
- 마이페이지 일정 조회 API 연결
- 일정 이름 수정
- 일정 공개 여부 설정
- 일정 삭제
- Header 토큰 확인
- 마이페이지 로딩창 생성
=> [FE] 마이페이지 일정 조회 API 연결

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/RegionController.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Schedule.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/RegionService.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/dto/ScheduleListResponse.java, BE/newsainturtle/src/test/java/com/newsainturtle/schedule/repository/ScheduleMemberRepositoryTest.java, BE/newsainturtle/src/test/java/com/newsainturtle/user/service/UserServiceTest.java
=> [BE] 일정 조회시 지역 정보 추가 API 작성

FE/src/features/user/myPage/myProfile/MyProfileEdit.tsx, FE/src/slices/authSlice.ts
close #217 
- 회원탈퇴 API 연결
- 탈퇴 및 로그아웃 시 local storage, session storage clear
=> [FE] 회원탈퇴 API 연결

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/BasicLocationRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/LocationResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Location.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/LocationService.java
=> [BE] Location 장소 컬럼 수정

FE/nginx.conf
=> [BE] Front nginx.conf 파일 추가

FE/src/api/Api.ts, FE/src/features/user/myPage/mySchedule/MyScheduleList.tsx, FE/src/features/user/myPage/mySchedule/MyScheduleListItem.tsx
close #222 
- 기존 고정 코드 수정 및 지역 정보 API 연결
- 지역 이미지, 지역 이름, 디데이 출력
=> [FE] 마이페이지 일정 조회 시 지역 정보 연동 수정

FE/package-lock.json, FE/package.json, FE/src/components/Button.tsx, FE/src/features/main/Components/MainDestinationModal.tsx, FE/src/features/main/MainDestinationsList.tsx, FE/src/features/schedule/create/CreateMap.tsx, FE/src/features/schedule/create/buttons/PlaceAddModal.tsx, FE/src/features/schedule/create/info/InfoLocal.tsx, FE/src/features/schedule/create/search/SearchList.tsx, FE/src/features/schedule/edit/EditFullScheduleList.tsx, FE/src/pages/ScheduleEditPage.tsx, FE/src/slices/scheduleCreateSlice.ts
- 공통 버튼 디자인 수정
- redux region id 추가 & 사용 코드 수정
- 일정 생성 API 수정
- xsel 설치
=> [FE] redux region id 추가 & 사용 코드 수정 & xsel 설치

BE/newsainturtle/src/main/java/com/newsainturtle/common/config/SecurityConfig.java, FE/src/App.tsx, FE/src/features/temp/InsertData.tsx, FE/src/pages/DataPage.tsx
close #231 
- Location 관련 데이터 삽입을 위한 임시 코드 작성
=> [FE] Location 관련 데이터 삽입을 위한 임시 코드 작성

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/BasicLocationRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/CustomLocationRepository.java
=> [BE] 장소 검색 API 포함단어 수정

FE/src/features/schedule/create/search/SearchListCard.tsx, FE/src/features/schedule/edit/Edit.module.css, FE/src/features/schedule/edit/search/SearchList.tsx, FE/src/pages/ScheduleEditPage.tsx
close #213 
- 일정 수정 페이지 내 장소 검색 기능 추가
- 일정 수정 페이지 내 장소 등록 기능 추가
=> [FE] 일정 수정 페이지 내 장소 검색, 장소 추가 버튼 및 기능 추가

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/constant/ScheduleSuccessConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/ScheduleController.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/ScheduleRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
=> [BE] 여행기 조회 API 작성

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/LocationService.java
=> [BE] 사용자 장소 검색 API 수정

FE/src/api/Api.ts, FE/src/features/main/Components/MainDestinationModal.tsx, FE/src/features/schedule/create/info/InfoLocal.tsx, FE/src/features/schedule/create/info/InfoLocalSelect.tsx, FE/src/features/schedule/create/search/SearchCardInfoModal.tsx, FE/src/features/schedule/create/search/SearchList.tsx
close #234
- 불필요한 API 제거
- 일정 만들기 redux 초기화
- 일정생성 페이지 지역 변경 select 컴포넌트 생성
=> [FE] 일정 생성 후 장소 변경 컴포넌트 수정 & 장소 상세 조회 내용 추가

FE/package.json, FE/src/api/firebaseConfig.ts, FE/src/components/Header.tsx, FE/src/features/user/myPage/myProfile/MyProfile.module.css, FE/src/features/user/myPage/myProfile/MyProfile.tsx, FE/src/features/user/myPage/myProfile/MyProfileEdit.tsx, FE/src/slices/authSlice.ts
close #229 
- firebase 설치 (npm i 필 ! !)
- 프로필 이미지 업로드 API 연결
- 프로필 이미지 헤더, 마이페이지 적용
=> [FE] 유저 프로필 사진 등록 및 변경 API 연결

FE/package-lock.json, FE/src/features/schedule/create/CreateButtons.tsx, FE/src/pages/ScheduleCreatePage.tsx
close #251 
- 사용자 장소 담은 리스트 제한하기
- 설정한 일자만큼 호텔 리스트 채우기
- 설정한 일자만큼 최소 장소 리스트 채우기
- 시작 끝 장소 채우기
- 일정 생성 시도 시 리스트에 못 채우면 Toast 보여주기
=> [FE] 사용자 장소 담은 리스트 제한하기

FE/src/features/main/Components/MainCarousel.tsx, FE/src/features/main/Components/MainCarouselCard.tsx, FE/src/features/main/Main.module.css, FE/src/features/main/MainDestinations/MainDestinationsItem.tsx, FE/src/features/main/MainTravelLog/MainTravelLog.tsx, FE/src/features/main/MainTravelLog/MainTravelLogItem.tsx, FE/src/features/main/MainTravelLog/MainTravelLogModal.tsx, FE/src/features/user/myPage/myProfile/MyProfile.tsx, FE/src/features/user/myPage/mySchedule/MyScheduleList.tsx, FE/src/pages/MyPage.tsx, FE/src/slices/mainSlice.ts
close #244 
- 여행기 API 연결 및 CSS 수정
- 여행기 모달 CSS 수정
- 여행'지' 모달 애니메이션 적용
- 인기 여행지 모달 연결
=> [FE] 여행기 API 연결 및 모달 생성, 수정

FE/src/features/main/MainDestinations/MainDestinationModal.tsx, FE/src/features/schedule/create/buttons/PlaceAddModal.tsx, FE/src/features/schedule/create/info/InfoLocal.tsx, FE/src/features/schedule/create/info/InfoLocalSelect.tsx, FE/src/features/schedule/create/search/SearchList.tsx, FE/src/slices/scheduleCreateSlice.ts
close #256 
- 선택 지역 영어 이름 저장 및 반영
- 사용자 장소 추가 검색 오류 해결
=> [FE] 선택 지역 영어 이름 저장 및 반영

FE/src/features/schedule/edit/Edit.module.css, FE/src/features/user/login/Login.tsx, FE/src/features/user/login/LoginSocial.tsx, FE/src/pages/ScheduleEditPage.tsx
close #262 
- 카카오 로그인 API 주소 변경
- 일정 이름 보내는 커밋은 여기에 왜 들어가 있는지 모르겠음 . . . . . . . . . . . . . .
=> [FE] 카카오 로그인 API 주소 변경

FE/src/features/user/myPage/mySchedule/MyScheduleListItem.tsx
close #266 
- 일정 공개/비공개 오류 수정
- 삭제할 브랜치에 커밋해부림 ㅠ 미안 ~!
=> [FE] 일정 공개/비공개 오류 수정

FE/src/features/user/notice/Notice.tsx, FE/src/slices/authSlice.ts
=> [FE] 소켓 통신 오류 수정

BE/newsainturtle/src/main/java/com/newsainturtle/notification/service/WebSocketService.java
close #269
- 실시간 알림 오류 수정
- 세션 닫는 로직에 오류가 있어서 수정
- 세션을 열때 이메일이 없는 경우 예외처리
=> [BE] 실시간 알림 오류 수정

BE/newsainturtle/src/main/java/com/newsainturtle/common/config/SecurityConfig.java
close #274 
- 메인페이지 여행기 조회 접근 권한 변경
=> [BE] 메인페이지 여행기 조회 접근 권한 변경

FE/src/components/Header.tsx, FE/src/features/main/MainTravelLog/MainTravelLog.tsx, FE/src/features/user/login/Login.tsx, FE/src/slices/authSlice.ts
close #268 
- 토큰 에러 시 로그아웃 후 메인 이동
- 토큰 문구 출력 시 로그인 조건 확인
- 로그아웃 시 authSlice - userInfo 초기화
=> [FE] 토큰 만료 시 로그인 리다이렉트 수정

FE/src/components/Header.tsx, FE/src/components/HeaderMobile.tsx, FE/src/features/user/login/Login.tsx, FE/src/features/user/myPage/myProfile/MyProfileEdit.tsx, FE/src/features/user/notice/Socket.ts, FE/src/slices/authSlice.ts
=> [FE] 소켓 연결 오류 수정

FE/public/index.html, FE/src/features/user/notice/Notice.tsx, FE/src/features/user/notice/Socket.ts
=> [FE] 로그인 소켓 오류 수정

BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/kakao/KakaoInfoMapResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/kakao/KakaoInfoResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/kakao/KakaoNicknameResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/kakao/KakaoTokenResponse.java
close #284 
- 카카오 로그인 접근제어자 변경
=> [BE] 카카오 로그인 접근제어자 변경

FE/src/components/Header.tsx, FE/src/features/user/login/Login.tsx, FE/src/slices/authSlice.ts
close #282 
- 토큰 관련 변수 삭제
- 토큰 에러 시 로그아웃 & 메인페이지 리다이렉트
=> [FE] 토큰 에러 시 로그아웃 & 메인페이지 리다이렉트

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/constant/ScheduleSuccessConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/ScheduleController.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/LocationResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/LocationSetRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleLocationSetRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleLocationSetResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/webDto/OpenStreetInfoResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/webDto/OpenStreetResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Schedule.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/LocationService.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
=> [BE] 일정에 포함된 장소 세팅 API 작성

FE/src/features/user/myPage/myFriends/MyFriends.module.css, FE/src/features/user/myPage/myFriends/MyFriends.tsx, FE/src/features/user/myPage/myProfile/MyProfile.tsx, FE/src/features/user/myPage/mySchedule/MySchedule.tsx, FE/src/pages/MyPage.tsx, FE/src/pages/ScheduleEditPage.tsx
close #277 
- 마이페이지 타이틀 삭제 및 버튼 컬러 추가
- 일정 취소 시 마이페이지로 가는 오류 수정
- 친구 목록 너비 수정
=> [FE] 마이페이지 타이틀 삭제 및 버튼 컬러 추가

FE/public/index.html, FE/src/App.tsx, FE/src/components/Header.tsx, FE/src/features/user/notice/Notice.tsx, FE/src/features/user/notice/NoticeToast.tsx, FE/src/features/user/notice/Socket.ts
close #280 
- 새로고침 시 소켓 연결 오류 해결
- 알림 토스트 메시지 기능 추가
=> [FE] 알림 메시지 출력 및 오류 수정

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/LocationSetRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
close #296
- 장소리스트 설정 Dto 오타 수정
=> [BE] 장소리스트 설정 Dto 오타 수정

FE/src/App.tsx, FE/src/features/user/notice/Socket.ts
close #299 
- 새로고침 시 소켓 연결 오류 수정
=> [FE] 새로고침 시 소켓 연결 오류 수정

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/BasicLocationRepository.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/LocationService.java
=> [BE] 추천리스트 개수 제한

FE/src/App.tsx, FE/src/components/Header.tsx, FE/src/features/user/login/Login.tsx, FE/src/features/user/myPage/myFriends/MyFriends.tsx, FE/src/features/user/myPage/myFriends/MyFriendsList.tsx, FE/src/features/user/myPage/myProfile/MyProfile.tsx, FE/src/features/user/notice/NoticeItem.tsx, FE/src/features/user/notice/NoticeToast.tsx, FE/src/features/user/notice/Socket.ts, FE/src/pages/MyPage.tsx, FE/src/slices/friendSlice.ts
close #188 
- 친구 수 렌더링 오류 수정
- 실시간 알림 오류 수정
- 친구 목록 slice 저장
- 친구 삭제 후 화면 재로딩
- 알림 삭제 후 화면 재로딩
=> [FE] 실시간 화면 렌더링 오류 수정

FE/src/App.tsx, FE/src/features/user/login/Login.tsx, FE/src/features/user/notice/NoticeToast.tsx, FE/src/pages/LoginPage.tsx
close #309 
- 알림 오류 수정
- 알림 메시지 위치 변경
=> [FE] 알림 오류 수정

FE/src/components/HeaderMobile.tsx, FE/src/components/css/Header.module.css
close #292 
- 모바일 반응형 프로필 사진, 이름 변경
=> [FE] 모바일 반응형 프로필 사진, 이름 변경

FE/src/api/Api.ts, FE/src/features/user/myPage/mySchedule/MySchedule.module.css, FE/src/features/user/myPage/mySchedule/MyScheduleInviteModal.tsx, FE/src/features/user/myPage/mySchedule/MyScheduleList.tsx, FE/src/features/user/myPage/mySchedule/MyScheduleListItem.tsx, FE/src/features/user/myPage/mySchedule/MyScheduleShareModal.tsx
close #293 
- 친구 공유 모달 컴포넌트 생성
- 내 일정 친구 공유 API 연결
- 내 일정 아닐 시 일정 수정 제한
- 일정 선택장소 개수 출력
=> [FE] 내 일정 친구 공유 API 연결

FE/src/features/schedule/edit/fullList/EditDayScheduleList.tsx, FE/src/features/schedule/edit/fullList/EditFullScheduleList.tsx, FE/src/features/schedule/edit/fullList/EditScheduleItem.tsx, FE/src/pages/ScheduleEditPage.tsx
=> [FE] 일정 생성 ↔ 수정 데이터 연결 

FE/src/features/main/Components/MainCarousel.tsx, FE/src/features/main/MainDestinations/MainDestinationsFilter.tsx, FE/src/features/main/MainDestinations/MainDestinationsItem.tsx, FE/src/features/main/MainDestinations/MainDestinationsList.tsx, FE/src/features/main/MainTravelLog/MainTravelLog.tsx, FE/src/features/main/MainTravelLog/MainTravelLogItem.tsx, FE/src/slices/mainSlice.ts
close #319 
- 메인페이지 여행기 필터링
- 메인페이지 여행기 - 여행지 이미지 출력
=> [FE] 메인페이지 여행지 필터링, 여행기 이미지 출력

FE/src/features/schedule/edit/fullList/EditDayScheduleList.tsx, FE/src/features/schedule/edit/fullList/EditFullScheduleList.tsx, FE/src/features/user/myPage/myFriends/MyFriends.module.css, FE/src/features/user/myPage/mySchedule/MySchedule.module.css, FE/src/features/user/myPage/mySchedule/MyScheduleListItem.tsx, FE/src/pages/ScheduleEditPage.tsx
close #323 
- 권한 없는 회원 접근 시 일정 추가/저장 버튼 삭제
=> [FE] 일정 공유 시 일정 목록 확인 연결 

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleLocationSetResponse.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
=> [BE] 일정 장소 거리 값 추가

FE/src/App.tsx, FE/src/features/user/login/Login.tsx, FE/src/features/user/myPage/myFriends/MyFriendsList.tsx, FE/src/features/user/notice/Notice.module.css, FE/src/features/user/notice/Notice.tsx, FE/src/features/user/notice/NoticeItem.tsx
close #332 
- 알림 개수 실시간 반영되도록 수정
- 카카오 로그인 시 소켓 연결 오류 수정
- 알림 처리 후 친구 목록 업데이트 오류 수정
- 알림 처리 후 화면 렌더링 오류 수정
- 알림 목록 스크롤 추가
=> [FE] 알림 오류 및 CSS 수정

FE/src/features/schedule/create/CreateMap.tsx, FE/src/features/schedule/edit/EditMap.tsx
close #337 
- 지도 마커 클릭 시 장소 정보 모달창 추가
- 지도 마커에 일정 순서 표시
=> [FE] 지도 마커 클릭 시 장소 정보 모달창 및 마커 순서 추가

BE/newsainturtle/src/main/java/com/newsainturtle/schedule/constant/ScheduleSuccessConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/ScheduleController.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Schedule.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
=> [BE] 일정 수정 API 작성

FE/src/features/schedule/edit/KeepScheduleItem.tsx, FE/src/features/schedule/edit/fullList/EditScheduleItem.tsx, FE/src/features/user/myPage/mySchedule/MyScheduleListItem.tsx
#340 
- 시간 출력 형식 오류 수정
- 일정 아이템 삭제 시 머무는 시간 계산 기능 추가
- 마이페이지 -> 일정 수정 페이지 이동시간 출력 오류 수정
- 이동 시간 커스텀 시 시간 계산 기능 추가
- 장소 보관함 머무는 시간 화면 출력 삭제
=> [FE] 일정 수정 페이지 시간 계산 오류 수정 

FE/src/components/Loding.tsx, FE/src/components/css/Loding.module.css, FE/src/pages/ScheduleCreatePage.tsx
close #347
- 로딩 컴포넌트 제작
- 일정 생성 API 통신 지연될시 로딩 페이지 보이기
=> [FE] 로딩 컴포넌트 제작 및 구현

FE/src/features/main/MainTravelLog/MainTravelLog.tsx, FE/src/features/main/MainTravelLog/MainTravelLogItem.tsx
close #349 
- 메인페이지 여행기 코드 수정: type 설정
=> [FE] 메인페이지 여행기 코드 수정

FE/src/App.tsx, FE/src/features/schedule/edit/KeepScheduleItem.tsx, FE/src/features/schedule/edit/dayList/EditDayMoveList.tsx, FE/src/features/schedule/edit/fullList/EditDayScheduleList.tsx, FE/src/features/schedule/edit/fullList/EditScheduleItem.tsx, FE/src/features/user/myPage/myFriends/MyFriendsList.tsx, FE/src/features/user/myPage/myFriends/MyFriendsSearch.tsx, FE/src/features/user/myPage/myFriends/MyFriendsSearchItem.tsx, FE/src/features/user/myPage/mySchedule/MyScheduleListItem.tsx, FE/src/features/user/notice/Notice.tsx, FE/src/features/user/notice/NoticeItem.tsx, FE/src/pages/MyPage.tsx, FE/src/pages/ScheduleEditPage.tsx, FE/src/slices/mainSlice.ts, FE/src/slices/scheduleEditSlice.ts
#340 
- 일정 수정 API 연결
- 일정 보관함 초기화 함수 추가
- 일정 수정 시 일정 보관함 초기화 기능 추가
- 일정 아이템 defaultProps 추가
- 일정 아이템 중복 시 드래그 오류 수정
- 이동시간 저장 함수 추가
- 일정 -> 보관함 이동 시 시간표 계산 기능 추가
- alert 삭제
- 친구 삭제 모달창 수정
- 일정 보관함 삭제 기능 추가
- 일정 저장 후 로딩페이지 추가
- 불필요한 console.log 제거
=> [FE] 일정 수정 페이지 시간 계산 오류 수정 및 전체 코드 리팩토링

BE/newsainturtle/src/main/java/com/newsainturtle/user/dto/UserRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/user/exception/UserException.java
close #356 
- 백엔드 코드 사용하지 않는 코드 정리
=> [BE] 백엔드 코드 정리

BE/newsainturtle/src/main/java/com/newsainturtle/common/constant/CommonConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/friend/constant/FriendConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/friend/dto/FriendFollowRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/friend/dto/FriendRemoveRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/constant/NotificationConstant.java, BE/newsainturtle/src/main/java/com/newsainturtle/notification/dto/NotificationResponseRequest.java, BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/LocationController.java
close #360 
- 상수 클래스 final 클래스로 변경
- Request DTO 접근제어자 변경
=> [BE] 코드 리팩토링
